## Introduction to Numpy

- Creating Arrays
- Multi-dimensional arrays
- Randomly generated arrays
- Element-wise operations
  * Comparison operations
  * Logical operations
- Summarizing operations

In [64]:
# importing the numpy library
import numpy as np

In [65]:
# use an abbreviation to reach it easily
np

<module 'numpy' from 'C:\\Users\\ojare\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

### Creating Arrays

In [66]:
# one-dimensional array with zeros of size 5
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [67]:
# one-dimensional array with ones of size 5
np.ones(5)

array([1., 1., 1., 1., 1.])

In [68]:
# specifying the exact element to use in a one-dimensional array for this case 2.5 with full() method
# of size 10
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [69]:
# creating a one-dimensional array using the array() method and differrent elements
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [70]:
# accessing the third element using its index value
a[2]

3

In [71]:
# changing the value of the third element to 10
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [72]:
# using the arange() method to create an array of values of size 10 upto 10, i.e., from 0 to 9
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
# creating an array of values starting from 3 to 10, that is, 3 to 9
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [74]:
# using linspace to create an array of values between 0 and 1 of size 11
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Multi-dimensional arrays

In [75]:
# creating a multi-dimensional array with zeros of size(5rows by 2columns) 
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [76]:
# a 3rows by 3cols array
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
# accessing an element at the first row and second column using index values
n[0, 1]

2

In [78]:
# changing an element's values
n[0, 1] = 20

In [36]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [79]:
# accessing a row using its index value
n[2]

array([7, 8, 9])

In [80]:
# changing the values of a row
n[2] = [1, 1, 1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [82]:
# accessing a column using its index number
n[:, 1]

array([20,  5,  1])

In [83]:
# changine the values of a column
n[:, 2] = [0, 1, 2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

### Randomly generated arrays

In [42]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [43]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [44]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

### Element-wise operations

In [45]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [46]:
a + 1

array([1, 2, 3, 4, 5])

In [47]:
a * 2

array([0, 2, 4, 6, 8])

In [48]:
a / 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [51]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [52]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

### Comparison operations

In [56]:
a

array([0, 1, 2, 3, 4])

In [53]:
a >= 2

array([False, False,  True,  True,  True])

In [55]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [54]:
a > b

array([False, False,  True,  True,  True])

In [57]:
a[a > b]

array([2, 3, 4])

### Summarizing operations

In [59]:
a

array([0, 1, 2, 3, 4])

In [58]:
a.min()

0

In [60]:
a.max()

4

In [61]:
a.sum()

10

In [62]:
a.mean()

2.0

In [63]:
a.std()

1.4142135623730951