## Introduction to Numpy

- Creating Arrays
- Multi-dimensional arrays
- Randomly generated arrays
- Element-wise operations
  * Comparison operations
  * Logical operations
- Summarizing operations

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Users\\ojare\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

### Creating Arrays

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [9]:
a[2]

3

In [10]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])